# Generated by Django 3.2 on 2021-04-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default=None, max_length=100, verbose_name='Заголовок поста'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='create_date',
            field=models.DateField(auto_created=True, verbose_name='Дата создания'),
        ),
    ]
