# Generated by Django 3.2 on 2021-04-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210421_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-create_date'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='Категория поста'),
        ),
    ]
