# Generated by Django 3.2 on 2021-04-25 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210422_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True, verbose_name='Дата создания комментария')),
                ('name', models.CharField(max_length=100, verbose_name='Ваше имя')),
                ('text', models.TextField(verbose_name='Поля для вашего текста: ')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.posts')),
            ],
        ),
    ]
