version: '3'
services:
  web:
    build: .
    command: python3 manage.py migrate
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /usr/src/my_django/
    ports:
      - 8000:8000